---
name: test and coverage
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: make cover
      - name: Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
